### ISSUE TITLE
Enhancement: add timestamps to the output

### ISSUE THREAD

**Issue by zpah** [anko/xkbcat#1]
[xkbcat-timestamps.patch.txt](https://github.com/anko/xkbcat/files/2822213/xkbcat-timestamps.patch.txt)

**Comment by anko** [comment]
This program used to have that option, but I [removed it](https://github.com/anko/xkbcat/commit/5f73713f5bc7a9081054bfc2a6c9b36f766498af), to keep the source maximally trivial for even novices to review.

I recommend piping to [moreutils' `ts`](http://joeyh.name/code/moreutils/) in the readme, which [comes with options for](https://linux.die.net/man/1/ts) timestamp formatting, absolute/relative time, etc, all of which I wouldn't want to add options for.
