### ISSUE TITLE
[Feature Request] Also show mouse button activities

### ISSUE THREAD

**Issue by isjerryxiao** [anko/xkbcat#2]
Maybe we should also display XI_RawButtonPress.

**Comment by anko** [comment]
I want to keep this program doing only key logging, so it stays as simple as possible.

Your idea is interesting though! Feel free to fork this code to make it log more event types. I'd be happy to help if you need directions.

Also consider `xinput --test-xi2 --root` as an alternative data source. It verbosely logs all events for all devices (key presses, mouse buttons, mouse movements, touchpad touches, …). It is packaged in every distro I've used.
