### ISSUE TITLE
Holding keys dont work 

### ISSUE THREAD

**Issue by siduck** [anko/xkbcat#6]
Hi there @anko , great job with xkbcat!!  When I hold a key, it just prints the key one time 

https://user-images.githubusercontent.com/59060246/218289549-e9031d37-6db2-45fd-a1c5-152aa28ae479.mp4

**Comment by siduck** [comment]
nvm i switched to xinput

**Comment by anko** [comment]
Thanks for the report. You're right; xkbcat listens only for "raw events", which correspond 1-to-1 to key events received from the keyboard. There's no interpretation, like autorepeat or modifier key resolution.

I would be open to adding an `-autorepeat` flag. I created a new issue #7 with some notes. 

`xinput` is probably the best alternative for that use-case:

```sh
xinput --test-xi2 --root
```
